name: Remove ATATOOLS.ps1 if included in a Push

on:
  push:
    branches:
      - '**'

jobs:
  check-and-delete-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if ATATOOLS.ps1 exists
      id: check_existence
      run: |
        if [ -f "ATATOOLS.ps1" ]; then
          echo "ATATOOLS_exists=true" >> $GITHUB_OUTPUT
        else
          echo "ATATOOLS_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Delete ATATOOLS.ps1 if it exists
      if: steps.check_existence.outputs.ATATOOLS_exists == 'true'
      run: |
        git config --global user.email "ATATOOLS-action@noreply.github.com"
        git config --global user.name "ATATOOLS-action"
        git rm ATATOOLS.ps1
        git commit -m "Delete ATATOOLS.ps1 as it is not allowed"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
